version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: jobportal_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin834
      POSTGRES_DB: jobportal
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5446:5432"

  backend:
    build: ./Backend
    container_name: jobportal_backend
    restart: always
    ports:
      - "3014:3014"
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin834
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: jobportal
      PORT: 3014
    depends_on:
      - postgres

  browsing-jobs:
    build: ./browsing-jobs
    container_name: browsing_jobs_ui
    ports:
      - "8026:80"
    depends_on:
      - backend

  hr-side-posting:
    build: ./hr-side-posting
    container_name: hr_side_posting_ui
    ports:
      - "8027:80"
    depends_on:
      - backend

volumes:
  pgdata:

